// Shared integration flow, called by the isolated Railway harness.
import assert from 'node:assert/strict';
export async function runWorkflow({base,origin,actor,scopedActor}) {
assert.match(base,/^http:\/\/(localhost|127\.0\.0\.1):\d+$/);
async function call(path,options={},who=actor){const r=await fetch(base+path,{...options,headers:{...(who?{Cookie:who.cookie}:{}),...options.headers}});const body=await r.json().catch(()=>({}));return {status:r.status,body}}
let state;let checks=0;
async function refresh(who=actor){const res=await call('/api/workspace',{},who);assert.equal(res.status,200,JSON.stringify(res.body));if(who===actor)state=res.body;return res.body}
async function command(c,who=actor,expect=200){const s=who===actor?state:await refresh(who);const r=await call('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({...c,revision:s.revision,operationId:crypto.randomUUID()})},who);assert.equal(r.status,expect,JSON.stringify(r.body));if(expect===200&&who===actor)state=r.body;return r}
assert.equal((await call('/api/workspace',{},null)).status,401);checks++;
await refresh();assert.equal(state.data.mode,'sample');checks++;
const submitted=state.data.milestones.find(m=>m.id==='m3').submittedAt;
await command({type:'milestone',id:'m3',action:'accept',checks:[true,true,true]});assert.equal(state.data.milestones.find(m=>m.id==='m3').status,'Accepted');await refresh();assert.equal(state.data.milestones.find(m=>m.id==='m3').submittedAt,submitted);checks++;
await command({type:'milestone',id:'m4',action:'resolve',reason:'Test fixture: image access restored.'});assert.equal(state.data.milestones.find(m=>m.id==='m4').status,'In progress');checks++;
const op=crypto.randomUUID();const payload={type:'create',collection:'projects',values:{title:'Integration threshold test',description:'A test proposal for the budget threshold.',owner:'lead@example.test',sponsor:'sponsor@example.test',backup:'backup@example.test',start:'2026-10-01',due:'2026-10-20',budget:25000},revision:state.revision,operationId:op};
const created=await call('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)});assert.equal(created.status,200,JSON.stringify(created.body));state=created.body;const projectId=state.id;assert.equal(state.data.obligations.filter(o=>o.projectId===projectId).length,1);const repeat=await call('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)});assert.equal(repeat.status,200);assert.equal(repeat.body.data.projects.filter(p=>p.title==='Integration threshold test').length,1);checks++;
const stale={type:'create',collection:'members',values:{title:'Concurrency test',joined:'2026-09-09'},revision:state.revision,operationId:crypto.randomUUID()};const race=await Promise.all([0,1].map(i=>call('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({...stale,operationId:crypto.randomUUID(),values:{...stale.values,title:'Concurrency '+i}})})));assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);await refresh();checks++;
const blocked=await call('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://unrelated.example'},body:JSON.stringify({...stale,revision:state.revision})});assert.equal(blocked.status,403);checks++;
const form=new FormData();form.set('file',new File(['Atoll integration evidence'], 'integration-evidence.txt',{type:'text/plain'}));form.set('projectId','ac-01');const uploaded=await call('/api/files',{method:'POST',headers:{Origin:origin},body:form});assert.equal(uploaded.status,200,JSON.stringify(uploaded.body));state=uploaded.body;const fileId=uploaded.body.fileId;const downloaded=await fetch(base+'/api/files/'+fileId,{headers:{Cookie:actor.cookie}});assert.equal(downloaded.status,200);assert.equal(await downloaded.text(),'Atoll integration evidence');checks++;
await command({type:'member_access',values:{name:'Scoped lead',email:'scoped-lead@example.test',role:'Project lead',projects:['ac-02'],governance:false}});const peer=scopedActor;const scoped=await refresh(peer);assert.equal(scoped.data.projects.length,1);assert.equal(scoped.data.projects[0].id,'ac-02');assert.equal(scoped.data.members.length,0);assert.equal(scoped.data.transactions.length,0);assert.equal(scoped.data.files.length,0);assert.equal((await call('/api/files/'+fileId,{},peer)).status,403);await command({type:'milestone',id:'m3',action:'reopen',reason:'Unauthorized cross-project change'},peer,400);checks++;
await command({type:'mode_switch',mode:'live'});assert.equal(state.data.mode,'live');assert.equal(state.data.projects.length,0);assert.equal(state.data.obligations[0].due,'2026-11-22');await command({type:'mode_switch',mode:'sample'});assert.equal(state.data.mode,'sample');assert.ok(state.data.files.some(f=>f.id===fileId));checks++;
// Complete a review/export flow using test evidence. This is explicitly sample data.
for(const t of state.data.transactions.filter(t=>t.status!=='Reconciled'))await command({type:'reconcile',id:t.id,fileId});
for(const gate of ['finance','compliance','committee','agm','signatures'])await command({type:'report',id:'report1',action:'approve',gate,reason:'Integration-test sample approval',fileId});
await command({type:'report',id:'report1',action:'lock'});
const exported=await call('/api/export/report1',{method:'POST',headers:{Origin:origin}});assert.equal(exported.status,200,JSON.stringify(exported.body));state=exported.body;const exportId=exported.body.fileId;assert.equal(state.data.reports[0].status,'Exported');assert.equal(state.data.submissions.length,0);
const zipRes=await fetch(base+'/api/files/'+exportId,{headers:{Cookie:actor.cookie}});assert.equal(zipRes.status,200);const bytes=new Uint8Array(await zipRes.arrayBuffer());assert.equal(new DataView(bytes.buffer).getUint32(0,true),0x04034b50);checks++;
await command({type:'submission',reportId:'report1',date:new Date().toISOString().slice(0,10),method:'Email',reference:'TEST-FILING-001',fileId});assert.equal(state.data.submissions[0].exportId,exportId);assert.equal(state.data.submissions[0].status,'Filed');checks++;
return {checks,state,fileId,exportId};
}
