'use client';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {ArrowRight,CalendarDays,ExternalLink,Upload,FileText,Check} from 'lucide-react';
import {useApp,Button,Status,Facts,Notice,FileLink,f} from './ui';
import {formatDate,formatTime,money,type Collection} from '@/lib/model';
export default function RecordDetail({selection,onClose}:{selection:{collection:Collection;id:string}|null;onClose:()=>void}){const {data,go,run,form}=useApp();const r=selection?(data[selection.collection] as any[]).find(r=>r.id===selection.id):null;const kind=selection?.collection;return <Sheet open={!!r} onOpenChange={v=>{if(!v)onClose()}}>{r&&<SheetContent className="record-sheet"><SheetHeader><div className="eyebrow">{kind?.toUpperCase()}</div><SheetTitle>{r.title}</SheetTitle><SheetDescription>Details, evidence, and decisions retained with this record.</SheetDescription></SheetHeader><div className="sheet-body"><Status value={r.status}/>
 {kind==='obligations'&&<><p className="panel-copy">{r.description}</p><Facts items={[["Authority",r.authority],['Due date',formatDate(r.due,true)],['Responsible owner',r.owner]]}/>{r.ruleId&&<a className="text-link" href={data.rules.find(x=>x.id===r.ruleId)?.source} target="_blank" rel="noreferrer">View governing source <ExternalLink size={14}/></a>}<h4>Readiness checklist</h4><div className="obligation-checklist">{r.checklist.map((c:any,i:number)=><label key={i}><Checkbox checked={c.done} disabled={['Filed','Accepted','Closed'].includes(r.status)} onCheckedChange={done=>run({type:'checklist',id:r.id,index:i,done})}/><span>{c.label}</span></label>)}</div>{r.id==='o1'&&r.status!=='Closed'&&<Button primary onClick={()=>{onClose();go('governance')}}><CalendarDays size={16}/> Open meetings</Button>}{!['Filed','Accepted','Closed'].includes(r.status)&&r.id!=='o1'&&<Button primary onClick={()=>form({title:'Record obligation filing',description:'This records a submission that has already been sent. It requires an official reference and proof.',fields:[f('date','Date sent','date'),f('method','Submission method','select',{options:['Authority portal','Email','In person','Post']}),f('reference','Official reference'),f('fileId','Official filing proof','file')],submit:'Record filing',onSubmit:v=>run({type:'submission',obligationId:r.id,...v})})}>Record manual filing <ArrowRight size={16}/></Button>}{!['Filed','Accepted','Closed'].includes(r.status)&&<div className="spaced"><Button onClick={()=>form({title:'Record deadline applicability',initial:{due:r.due},fields:[f('due','Confirmed legal deadline','date'),f('reason','Source review and applicability decision','textarea')],submit:'Record deadline decision',onSubmit:v=>run({type:'deadline_decision',id:r.id,...v})})}>Record deadline decision</Button></div>}<Notice>Checklist ticks indicate preparation. Only a recorded filing and official proof establish submission.</Notice></>}
 {kind==='meetings'&&<><Facts items={[["Meeting type",r.type],['Scheduled for',formatDate(r.date,true)+' · '+r.time+' MVT'],['Location',r.location],['Required quorum',r.quorum],['Attendees',r.attendees]]}/><h4>Agenda</h4><p className="preserve-lines" dir="auto">{r.agenda}</p>{r.status==='Finalized'?<><h4>Approved minutes</h4><p className="preserve-lines" dir="auto">{r.minutes}</p><h4>Resolution</h4><p className="preserve-lines" dir="auto">{r.resolution}</p><Notice><Check size={17}/> Finalized {formatTime(r.finalizedAt)} · {r.present} present</Notice></>:<div className="spaced"><Button primary onClick={()=>form({title:'Finalize meeting minutes',initial:{minutes:r.minutes,resolution:r.resolution},description:'Record approved minutes and resolution text. Finalizing locks this meeting record.',fields:[f('present','Number present','number'),f('minutes','Approved minutes','textarea'),f('resolution','Exact resolution text','textarea'),f('confirm','Approval confirmed','checkbox',{help:'The minutes and resolution are approved and the recorded quorum was met.'}),...(r.type==='First general meeting'?[f('election','Committee election held','checkbox',{required:false,help:'Create the notification deadline from this actual election date.'})]:[])],submit:'Finalize minutes',onSubmit:v=>run({type:'meeting',id:r.id,...v})})}>Record approved minutes <ArrowRight size={16}/></Button></div>}</>}
 {kind==='transactions'&&<><Facts items={[["Date",formatDate(r.date,true)],['Type',r.type],['Amount',money(r.amount)],['Category',r.category],['Project',data.projects.find(p=>p.id===r.projectId)?.title||'Organization'] ]}/>{r.fileId?<FileLink id={r.fileId}/>:r.evidence?<Notice>Sample receipt reference: {r.evidence}</Notice>:<Notice tone="amber">A receipt or transaction evidence is missing.</Notice>}{r.status!=='Reconciled'&&<Button primary onClick={()=>form({title:'Reconcile transaction',fields:[f('fileId','Receipt / transaction evidence','file',{scope:'finance'})],submit:'Confirm reconciliation',onSubmit:v=>run({type:'reconcile',id:r.id,...v})})}><Upload size={16}/> Attach evidence & reconcile</Button>}</>}
 {kind==='projects'&&<><p className="panel-copy">{r.description}</p><Facts items={[["Programme area",r.category],['Lifecycle',r.status],['Planned start',formatDate(r.start,true)],['Final delivery',formatDate(r.due,true)],['Budget',money(r.budget)],['Accountable lead',r.owner],['Sponsor',r.sponsor],['Deputy',r.backup],['Approval',r.approvalRef||'Not recorded']]}/><Notice>{r.policy}. Automated transfers remain inactive.</Notice><Button primary onClick={()=>{onClose();go('project/'+r.id)}}>Open project workspace <ArrowRight size={16}/></Button>{['Active','Approved'].includes(r.status)&&<div className="spaced"><Button onClick={()=>form({title:'Record a time-limited pause',fields:[f('reason','Authorized reason','textarea'),f('due','Next review date','date')],submit:'Record pause',onSubmit:v=>run({type:'project',id:r.id,action:'pause',...v})})}>Record authorized pause</Button></div>}</>}
 {kind==='submissions'&&<><Facts items={[["Authority",r.authority],['Filed on',formatDate(r.date,true)],['Method',r.method],['Official reference',r.reference],['Exact version','v'+r.version]]}/><h4>Official filing proof</h4><FileLink id={r.fileId}/>{r.exportId&&<><h4>Exact filed package</h4><FileLink id={r.exportId}/></>}<div className="spaced"><Button primary onClick={()=>form({title:'Record authority response',fields:[f('status','Authority response','select',{options:['Accepted','Returned']}),f('reason','Response details','textarea'),f('fileId','Official response evidence','file')],submit:'Record official response',onSubmit:v=>run({type:'response',id:r.id,...v})})}>Record response <ArrowRight size={16}/></Button></div>{r.responseFileId&&<><h4>Authority response</h4><FileLink id={r.responseFileId}/></>}<h4>Submission history</h4><div className="timeline">{r.history.map((h:any)=><div key={h.id}><small>{formatTime(h.at)}</small><b>{h.action}</b><p>{h.detail}</p></div>)}</div></>}
 {kind==='activities'&&<><Facts items={[["Activity date",formatDate(r.date,true)],['Location',r.location],['Participants',r.participants],['Project',data.projects.find(p=>p.id===r.projectId)?.title]]}/><h4>Purpose</h4><p dir="auto">{r.description}</p><h4>Recorded output</h4><p dir="auto">{r.output}</p></>}
 {kind==='members'&&<><div className="spaced"><Button onClick={()=>form({title:'Update membership status',fields:[f('status','Membership status','select',{options:['Active','Departed']}),f('date','Effective date','date'),f('reason','Reason / decision reference','textarea')],onSubmit:v=>run({type:'record_status',collection:'members',id:r.id,...v})})}>Update membership</Button></div><Facts items={[["Membership",r.type],['Joined',formatDate(r.joined,true)],['Email',r.email||'Not provided']]}/><Notice>Private identity and contact details are excluded from report membership summaries.</Notice></>}
 {kind==='committee'&&<Facts items={[["Appointee",r.person],['Office',r.title],['Effective date',formatDate(r.date,true)],['Term end',formatDate(r.end,true)],['Event type',r.eventType||'Founding appointment']]}/>}
 {kind==='donations'&&<><Facts items={[["Funding source",r.donor],['Received',formatDate(r.date,true)],['Amount',money(r.amount)],['Restrictions',r.restriction]]}/><Notice>A linked income transaction is reused in the finance register and report schedules.</Notice></>}
 {kind==='assets'&&<><div className="spaced"><Button onClick={()=>form({title:'Update asset status',fields:[f('status','Asset status','select',{options:['In use','In storage','Disposed']}),f('date','Effective date','date'),f('reason','Reason / decision reference','textarea'),f('fileId','Disposal evidence','file',{required:false,scope:'finance',help:'Required for disposal.'})],onSubmit:v=>run({type:'record_status',collection:'assets',id:r.id,...v})})}>Update asset status</Button></div><Facts items={[["Asset class",r.category],['Acquired',formatDate(r.date,true)],['Value',money(r.value)],['Custodian',r.custodian],['Location',r.location]]}/></>}
 </div></SheetContent>}</Sheet>}
