import {uid,now,addDays,addMonths,type WorkspaceData,type Entry,type Milestone,type Collection,type History} from './model.ts';
export type Actor={name:string;email:string;role:string;governance:boolean;projects:string[]};
export function requireValue(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(message)}
const text=(v:any,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const required=(v:any,label:string,max=10000)=>{const s=text(v,max);requireValue(s,label+' is required.');return s};
const date=(v:any,label:string)=>{const s=required(v,label);requireValue(/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s).toISOString().slice(0,10)===s,label+' must be a valid date.');return s};
const positive=(v:any,label:string)=>{const n=Number(v);requireValue(Number.isFinite(n)&&n>=0,label+' must be zero or more.');return n};
const owner=(a:Actor)=>a.role==='System owner';
const compliance=(a:Actor)=>owner(a)||a.role==='Compliance secretary';
const finance=(a:Actor)=>compliance(a)||a.role==='Treasurer';
const governs=(d:WorkspaceData,a:Actor)=>d.mode==='sample'?owner(a):a.governance;
const assigned=(d:WorkspaceData,a:Actor,person:string)=>d.mode==='sample'?owner(a):person.toLowerCase()===a.email.toLowerCase();
function hasProject(d:WorkspaceData,a:Actor,id:string){requireValue(compliance(a)||a.projects.includes(id),'You do not have access to this project.');return find(d.projects,id)}
function find<T extends Entry>(arr:T[],id:string):T{const x=arr.find(x=>x.id===id);requireValue(x,'Record not found.');return x}
function event(d:WorkspaceData,a:Actor,action:string,detail:string,recordId?:string):History{const e={id:uid(),at:now(),actor:a.name,action,detail,recordId};d.audit.unshift(e);return e}
function file(d:WorkspaceData,id:string,projectId?:string){const f=find(d.files,id);requireValue(!projectId||f.projectId===projectId,'Evidence must belong to this project.');return f}
export function readiness(d:WorkspaceData,report:Entry){const year=Number(report.year);const tx=d.transactions.filter(t=>String(t.date).startsWith(String(year)));const acts=d.activities.filter(t=>String(t.date).startsWith(String(year)));const gaps:string[]=[];if(!report.narrative?.trim())gaps.push('Add the report narrative.');if(!tx.length&&!report.noneDeclared)gaps.push('Record finance activity or an explicit none declaration.');if(!acts.length&&!report.noneDeclared)gaps.push('Record activities or an explicit none declaration.');if(tx.some(t=>t.status!=='Reconciled'))gaps.push('Reconcile every transaction for the reporting year.');if(tx.some(t=>!t.evidence&&!t.fileId))gaps.push('Attach evidence to every transaction.');if(d.mode==='live'&&d.rules.some(r=>r.authority===report.authority&&r.status==='Needs review'))gaps.push('Review the applicable authority rules and deadline.');return gaps}
function snapshot(d:WorkspaceData,r:Entry){const yr=String(r.year);return {organization:d.organization,report:{id:r.id,title:r.title,year:r.year,version:r.version,narrative:r.narrative,due:r.due,authority:r.authority},approvals:r.approvals,membership:{active:d.members.filter(m=>m.status==='Active').length,joined:d.members.filter(m=>String(m.joined).startsWith(yr)).length},activities:d.activities.filter(x=>String(x.date).startsWith(yr)),transactions:d.transactions.filter(x=>String(x.date).startsWith(yr)),donations:d.donations.filter(x=>String(x.date).startsWith(yr)),assets:d.assets,acceptedResults:d.milestones.filter(m=>m.status==='Accepted'&&m.acceptedAt?.startsWith(yr)).map(m=>({id:m.id,projectId:m.projectId,title:m.title,result:m.result,version:m.version,evidence:m.evidence,fileId:m.fileId,submittedAt:m.submittedAt,acceptedAt:m.acceptedAt})),meetings:d.meetings.filter(m=>m.status==='Finalized'&&String(m.date).startsWith(yr)),noneDeclared:!!r.noneDeclared}}
export function applyCommand(d:WorkspaceData,c:any,a:Actor):{message:string;id?:string}{
 requireValue(c&&typeof c.type==='string','Choose an action.');
 if(c.type==='attach_evidence'){
  requireValue(compliance(a),'Governance and compliance access is required.');
  const kind=c.collection;requireValue(['organization','members','committee','meetings','obligations','submissions','rules'].includes(kind),'Unsupported document destination.');
  const r=kind==='organization'?d.organization:find(d[kind as Collection],c.id);
  const proof=file(d,required(c.fileId,'Supporting document'));
  requireValue(!proof.projectId&&!proof.scope?.startsWith('report:')&&proof.scope!=='finance','Use a governance or compliance document.');
  const reason=required(c.reason,'Document purpose / version note');
  r.fileIds=[...new Set([...(r.fileIds||[]),proof.id])];
  event(d,a,'Supporting document attached',proof.title+' · '+reason,c.id);
  return {message:'Document attached. Earlier evidence is retained.'};
 }
 if(c.type==='complete_internal'){
  requireValue(compliance(a),'Compliance access is required.');const r=find(d.obligations,c.id);
  requireValue(r.authority==='Internal governance','Official duties require a recorded filing.');
  requireValue(!['Closed','Filed','Accepted'].includes(r.status),'This obligation is already complete.');
  requireValue(r.checklist.length>0&&r.checklist.every((item:any)=>item.done),'Complete the readiness checklist first.');
  file(d,required(c.fileId,'Completion evidence'));const result=required(c.reason,'Completed result');
  r.status='Closed';r.completedAt=now();r.result=result;r.fileIds=[...new Set([...(r.fileIds||[]),c.fileId])];
  event(d,a,'Internal obligation completed',result,r.id);return {message:'Completion and supporting evidence retained.'};
 }
 if(c.type==='member_details'){
  requireValue(compliance(a),'Governance record access is required.');
  const r=find(d.members,c.id),p=c.values||{};
  const reason=required(p.reason,'Correction reason and source');
  const next:Record<string,string>={title:required(p.title,'Member name',250)};
  for(const key of ['email','phone','address','occupation','reviewNotes'])next[key]=text(p[key],key==='reviewNotes'?4000:1000);
  requireValue(!next.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.email),'Enter a valid email.');
  for(const key of ['joined','applicationDate','birthDate']){
   next[key]=p[key]?date(p[key],key):'';
   requireValue(!next[key]||next[key]<=now().slice(0,10),'A confirmed member date cannot be in the future.');
  }
  const previous=Object.fromEntries(Object.keys(next).map(key=>[key,r[key]??'']));
  Object.assign(r,next);
  r.detailChanges=[...(r.detailChanges||[]),{...event(d,a,'Member details corrected',reason,r.id),previous,updated:next}];
  return {message:'Member details corrected. Source documents and previous values are retained.'};
 }
 if(c.type==='create'){
  const kind=c.collection as Collection;const p=c.values||{};const projectKinds=['projects','milestones','activities'];requireValue(projectKinds.includes(kind)?compliance(a)||['Project lead','Project sponsor'].includes(a.role):['transactions','donations','assets'].includes(kind)?finance(a):compliance(a),'You cannot create this type of record.');
  requireValue(['projects','milestones','activities','meetings','members','committee','transactions','donations','assets','obligations','reports'].includes(kind),'Unsupported record type.');
  const r:Entry={id:uid(),title:required(p.title,'Name',250),status:'Recorded'};
  if(kind==='projects'){
   const start=date(p.start,'Start date'),due=date(p.due,'Final delivery');requireValue(due>=start,'Final delivery must follow the start.');const lead=required(p.owner,'Accountable lead',250),sponsor=required(p.sponsor,'Project sponsor',250);requireValue(lead!==sponsor,'Lead and sponsor must be distinct people.');Object.assign(r,{code:'AC–'+String(d.projects.length+1).padStart(2,'0'),category:text(p.category,100)||'Community',description:required(p.description,'Purpose'),start,due,owner:lead,sponsor,backup:required(p.backup,'Backup',250),budget:positive(p.budget,'Budget'),status:'Proposed',health:'Awaiting approval',approved:false,policy:'Draft · not activated'});
   const projectRule=d.rules.find(x=>x.id==='r2');
   const threshold=projectRule?.threshold;
   if(d.mode==='live'&&(typeof threshold!=='number'||projectRule?.status==='Needs review'))d.obligations.push({id:uid(),title:'Review project notice applicability · '+r.title,status:'Action needed',authority:'Internal governance',owner:'Compliance secretary',projectId:r.id,ruleId:'r2',due:'',dueLabel:'Before project launch',description:'Confirm the applicable official project-notice rule and record any required filing. The source documents do not establish a reviewed budget threshold.',checklist:[{label:'Confirm the applicable source and threshold',done:false},{label:'Record any required notice and proof',done:false}]});
   if(typeof threshold==='number'&&!(d.mode==='live'&&projectRule?.status==='Needs review')&&r.budget>=threshold)d.obligations.push({id:uid(),title:'Project information notice · '+r.title,status:'Blocked',authority:'Registrar',owner:'Compliance secretary',projectId:r.id,ruleId:'r2',due:addDays(start,-1),description:'Blocking pre-start notice for a project meeting the configured MVR '+threshold+' threshold. The displayed date is the internal latest preparation date; filing is required before start.',checklist:[{label:'Record project approval',done:false},{label:'Approve the notice package',done:false},{label:'Record manual filing with proof',done:false}]});
  }
  if(kind==='milestones'){
   const pr=hasProject(d,a,required(p.projectId,'Project'));requireValue(!['Completed','Closed by decision'].includes(pr.status),'This project is closed.');const due=date(p.due,'Output due'),reviewDue=date(p.reviewDue,'Review due');requireValue(due<=pr.due&&reviewDue>=due&&reviewDue<=pr.due,'Output and review dates must leave time before final delivery.');const lead=required(p.owner,'Owner',250),reviewer=required(p.reviewer,'Reviewer',250);requireValue(lead!==reviewer,'Owner and reviewer must be distinct people.');const criteria=required(p.criteria,'Acceptance criteria').split('\n').map(x=>x.trim()).filter(Boolean);Object.assign(r,{projectId:pr.id,number:String(d.milestones.filter(m=>m.projectId===pr.id).length+1).padStart(2,'0'),owner:lead,reviewer,due,reviewDue,criteria,result:'',version:0,status:'Planned',commitmentAccepted:false,history:[],backup:pr.backup});
  }
  if(kind==='activities'){hasProject(d,a,required(p.projectId,'Project'));Object.assign(r,{date:date(p.date,'Activity date'),projectId:p.projectId,location:text(p.location,250),participants:positive(p.participants,'Participants'),description:required(p.description,'Purpose'),output:required(p.output,'Output'),status:'Completed'})}
  if(kind==='meetings')Object.assign(r,{date:date(p.date,'Meeting date'),type:required(p.type,'Meeting type',100),time:text(p.time,20)||'16:00',location:required(p.location,'Location',250),owner:a.email,attendees:required(p.attendees,'Attendees'),quorum:positive(p.quorum,'Quorum'),agenda:required(p.agenda,'Agenda'),minutes:'',resolution:'',status:'Scheduled'});
  if(kind==='members'){
   const joined=p.joined?date(p.joined,'Join date'):'';const applicationDate=p.applicationDate?date(p.applicationDate,'Application date'):'';
   requireValue((!joined||joined<=now().slice(0,10))&&(!applicationDate||applicationDate<=now().slice(0,10)),'A confirmed member date cannot be in the future.');
   if(p.fileId)file(d,p.fileId);
   Object.assign(r,{joined,applicationDate,email:text(p.email,250),phone:text(p.phone,100),type:text(p.type,100)||'Member',status:'Active',fileIds:p.fileId?[p.fileId]:[]});
  }
  if(kind==='committee'){
   const effective=date(p.date,'Effective date');Object.assign(r,{person:required(p.person,'Appointee',250),date:effective,end:date(p.end,'Term end'),eventType:required(p.eventType,'Change type'),status:'Active'});requireValue(r.end>=effective,'Term end must follow appointment.');const rule=d.rules.find(x=>x.id==='r3');const days=p.eventType==='First election'?(rule?.days??30):(rule?.changeDays??(d.mode==='sample'?15:null));d.obligations.push({id:uid(),title:'Committee notification · '+r.title,status:'Action needed',authority:'Registrar',owner:'Compliance secretary',due:days===null?'':addDays(effective,days),...(days===null?{dueLabel:'Confirm notification deadline'}:{}),ruleId:'r3',committeeId:r.id,description:days===null?'Confirm the notification deadline for this change against the applicable official source.':days+' days from the recorded '+p.eventType.toLowerCase()+'. Review the source rule before live filing.',checklist:[{label:'Confirm appointment and contact details',done:false},{label:'Attach resolution',done:false},{label:'Record submission and proof',done:false}]});
  }
  if(kind==='transactions')Object.assign(r,{date:date(p.date,'Transaction date'),type:p.type==='Income'?'Income':'Expense',amount:positive(p.amount,'Amount'),category:required(p.category,'Category',100),projectId:text(p.projectId,100),status:'Needs receipt'});
  if(kind==='donations'){Object.assign(r,{date:date(p.date,'Donation date'),donor:required(p.donor,'Donor',250),amount:positive(p.amount,'Amount'),restriction:required(p.restriction,'Restrictions',1000),transactionId:uid()});d.transactions.push({id:r.transactionId,title:r.title,date:r.date,type:'Income',amount:r.amount,category:'Donations',status:'Needs receipt',donationId:r.id,projectId:''})}
  if(kind==='assets')Object.assign(r,{date:date(p.date,'Acquisition date'),value:positive(p.value,'Value'),category:required(p.category,'Category',100),custodian:required(p.custodian,'Custodian',250),location:text(p.location,250),status:'In use'});
  if(kind==='obligations')Object.assign(r,{due:date(p.due,'Due date'),authority:required(p.authority,'Authority',100),owner:required(p.owner,'Owner',250),description:required(p.description,'Requirement'),ruleId:text(p.ruleId,100),status:'Action needed',checklist:required(p.checklist,'Checklist').split('\n').filter(Boolean).map(label=>({label,done:false}))});
  if(kind==='reports'){const year=positive(p.year,'Year');requireValue(year>=2026&&year<=2100,'Choose a valid reporting year.');if(p.authority==='MIRA')requireValue(d.organization.mira==='Approved','MIRA reports apply only after approved charity status is recorded.');Object.assign(r,{authority:p.authority==='MIRA'?'MIRA':'Registrar',year,due:date(p.due,'Due date'),status:'Draft',version:1,narrative:'',gates:{finance:false,compliance:false,committee:false,agm:false,signatures:false},approvals:[],versions:[]})}
  (d[kind] as Entry[]).push(r);event(d,a,'Record created',r.title,r.id);return {message:r.title+' created.',id:r.id};
 }
 if(c.type==='milestone'){
  const m=find(d.milestones,c.id);hasProject(d,a,m.projectId);const action=c.action;requireValue(m.status!=='Accepted'||action==='reopen','Accepted records are read-only. Create a correction cycle instead.');
  if(action==='accept'){requireValue(assigned(d,a,m.reviewer),'Only the assigned reviewer can accept this result.');requireValue(m.status==='Submitted for review','Only submitted evidence can be accepted.');requireValue(!m.blocked,'Resolve the blocker before accepting this result.');requireValue(c.checks?.length===m.criteria.length&&c.checks.every((x:any)=>x===true),'Verify every acceptance criterion.');m.status='Accepted';m.acceptedAt=now();m.acceptedBy=a.email;m.history.push(event(d,a,'Result accepted',m.title+' · evidence v'+m.version,m.id));return {message:'Milestone accepted and moved to Completed.',id:m.id}}
  if(action==='submit'){requireValue(assigned(d,a,m.owner),'Only the accountable owner can submit this milestone.');requireValue(['Planned','In progress','Changes requested'].includes(m.status),'This evidence is already awaiting review.');const result=required(c.result,'Substantive result');requireValue(result.length>=30,'Describe the concrete output in at least 30 characters.');if(c.fileId){const f=file(d,c.fileId,m.projectId);m.fileId=f.id;m.evidence=f.title}else{requireValue(c.structured===true,'Attach evidence or confirm a structured outcome.');m.evidence='Structured result record'}m.result=result;m.submittedAt=now();m.version++;m.status='Submitted for review';m.history.push(event(d,a,'Evidence submitted',m.title+' · v'+m.version,m.id));return {message:'Evidence submitted. Completion awaits reviewer acceptance.'}}
  if(action==='return'){requireValue(assigned(d,a,m.reviewer),'Only the assigned reviewer can return evidence.');requireValue(m.status==='Submitted for review','There is no pending submission.');m.status='Changes requested';m.returnReason=required(c.reason,'Acceptance gaps');m.history.push(event(d,a,'Changes requested',m.returnReason,m.id));return {message:'Evidence returned with acceptance gaps.'}}
  if(action==='block'){requireValue(assigned(d,a,m.owner)||assigned(d,a,m.reviewer),'Only this milestone’s owner or reviewer may report a blocker.');m.blocked=true;m.blocker=required(c.reason,'Blocker and attempted resolution');m.unblockOwner=required(c.owner,'Unblock owner',250);m.unblockDue=date(c.due,'Resolution deadline');m.history.push(event(d,a,'Blocker reported',m.blocker,m.id));return {message:'Blocker recorded. Independent work remains active.'}}
  if(action==='resolve'){requireValue(assigned(d,a,m.unblockOwner||'')||assigned(d,a,m.reviewer),'Only the unblock owner or reviewer may resolve this blocker.');requireValue(m.blocked,'This milestone has no open blocker.');m.blocked=false;m.history.push(event(d,a,'Blocker resolved',required(c.reason,'Resolution evidence'),m.id));return {message:'Blocker resolved. The milestone remains Active until accepted.'}}
  if(action==='reopen'){requireValue(assigned(d,a,m.reviewer)||governs(d,a),'A reviewer or governance decision-maker must authorize corrections.');const {cycles,...acceptedCycle}=m;m.cycles=[...(cycles||[]),structuredClone(acceptedCycle)];m.evidence=undefined;m.status='Changes requested';m.acceptedAt=undefined;m.submittedAt=undefined;m.fileId=undefined;m.result='';m.history.push(event(d,a,'Correction cycle opened',required(c.reason,'Correction reason'),m.id));return {message:'A new correction cycle is active. Earlier acceptance is preserved.'}}
  if(action==='commit'){requireValue(assigned(d,a,m.owner),'Only the assigned owner can accept this commitment.');m.commitmentAccepted=true;m.history.push(event(d,a,'Commitment accepted','Scope, criteria, dates and backup route accepted.',m.id));return {message:'Commitment accepted.'}}
  throw new Error('Unknown milestone action.');
 }
 if(c.type==='project'){
  const p=hasProject(d,a,c.id);
  if(c.action==='approve'){requireValue(governs(d,a),'Record distinct governance authority before approving a project. Technical access alone is insufficient.');requireValue(p.status==='Proposed','Only a proposed project can be approved.');p.approvalRef=required(c.reason,'Approval resolution');p.approved=true;p.status='Approved';event(d,a,'Project approved',p.approvalRef,p.id);return {message:'Project approved. Complete the launch checks before starting.'}}
  if(c.action==='backup'){requireValue(assigned(d,a,p.backup),'Only the named deputy can accept the backup route.');p.backupAccepted=true;event(d,a,'Backup accepted',p.title+' · scoped standing backup responsibility',p.id);return {message:'Backup acceptance recorded.'}}
  if(c.action==='start'){requireValue(assigned(d,a,p.owner)||governs(d,a),'Only the accountable lead or governance decision-maker can start the project.');requireValue(p.approved,'Record project approval first.');const ms=d.milestones.filter(m=>m.projectId===p.id);requireValue(ms.length>0&&ms.every(m=>m.commitmentAccepted),'Every milestone needs an accepted commitment.');requireValue(p.backupAccepted,'The named deputy must accept the backup route.');requireValue(d.mode==='sample'||p.continuityApproved,'The continuity policy must be formally approved before live launch. Live policy activation is not yet enabled.');requireValue(!d.obligations.some(o=>o.projectId===p.id&&!['Filed','Accepted','Closed'].includes(o.status)),'File the blocking pre-start notice with proof first.');p.status='Active';event(d,a,'Project started',p.title,p.id);return {message:'Project started.'}}
  if(c.action==='pause'){requireValue(governs(d,a),'A governance decision-maker must approve a pause.');p.status='Paused with review date';p.pauseReason=required(c.reason,'Pause reason');p.reviewDate=date(c.due,'Review date');event(d,a,'Time-limited pause',p.pauseReason,p.id);return {message:'Project paused with its owner and review date retained.'}}
  throw new Error('Unknown project action.');
 }
 if(c.type==='checklist'){requireValue(compliance(a),'Compliance access is required.');const o=find(d.obligations,c.id);requireValue(!['Filed','Accepted','Closed'].includes(o.status),'Filed records are immutable.');requireValue(Number.isInteger(c.index)&&!!o.checklist[c.index],'Checklist item not found.');o.checklist[c.index].done=!!c.done;o.status='In progress';event(d,a,'Checklist updated',o.title+' · '+o.checklist[c.index].label,o.id);return {message:'Checklist saved.'}}
 if(c.type==='meeting'){
  requireValue(compliance(a),'Governance record access is required.');const m=find(d.meetings,c.id);requireValue(m.status!=='Finalized','Finalized minutes are read-only. Record a new resolution for corrections.');m.minutes=required(c.minutes,'Minutes');m.resolution=required(c.resolution,'Resolution');const present=positive(c.present,'Present count');requireValue(present>=m.quorum&&m.quorum>0,'The recorded attendance must meet quorum.');requireValue(c.confirm===true,'Confirm that these are the approved minutes.');m.present=present;m.status='Finalized';m.finalizedAt=now();m.history=[event(d,a,'Minutes finalized',m.title,m.id)];if(m.type==='First general meeting'){const o=d.obligations.find(x=>x.id==='o1');if(o){o.status='Closed';o.meetingId=m.id;o.checklist.forEach((x:any)=>x.done=true)}if(c.election===true){const days=d.rules.find(r=>r.id==='r3')?.days??30;d.obligations.push({id:uid(),title:'First committee election notification',status:'Action needed',authority:'Registrar',due:addDays(m.date,days),owner:'Compliance secretary',ruleId:'r3',meetingId:m.id,description:'Calculated from the actual first election date.',checklist:[{label:'Record elected committee members',done:false},{label:'Attach approved election resolution',done:true},{label:'Submit notification and retain proof',done:false}]})}}return {message:'Minutes finalized. Applicable election notification created.'}
 }
 if(c.type==='reconcile'){requireValue(finance(a),'Finance access is required.');const t=find(d.transactions,c.id);requireValue(t.status!=='Reconciled','This transaction is already reconciled.');if(c.fileId){const f=file(d,c.fileId);t.fileId=f.id;t.evidence=f.title}requireValue(t.evidence,'Attach a receipt or transaction evidence first.');t.status='Reconciled';event(d,a,'Transaction reconciled',t.title,t.id);return {message:'Transaction reconciled.'}}
 if(c.type==='report'){
  requireValue(finance(a)||a.role==='Approver','Report access is required.');const r=find(d.reports,c.id);requireValue(finance(a)||a.projects.includes(r.id),'This report is outside your assigned scope.');const immutable=['Locked','Exported','Filed'].includes(r.status);
  if(c.action==='revise'){requireValue(immutable,'This report is already editable.');r.version++;r.status='Draft';r.gates={finance:false,compliance:false,committee:false,agm:false,signatures:false};r.approvals=[];delete r.exportId;event(d,a,'Report correction opened',required(c.reason,'Correction reason'),r.id);return {message:'New report version opened. Filed versions remain unchanged.'}}
  requireValue(!immutable,'This version is locked. Create a new version to edit it.');
  if(c.action==='save'){r.narrative=required(c.narrative,'Report narrative');r.noneDeclared=!!c.noneDeclared;r.status='Draft';r.gates={finance:false,compliance:false,committee:false,agm:false,signatures:false};r.approvals=[];event(d,a,'Draft updated',r.title,r.id);return {message:'Draft saved; approvals will be collected for this content.'}}
  if(c.action==='validate'){const gaps=readiness(d,r);r.status=gaps.length?'Validation failed':'Ready for review';r.validation=gaps;event(d,a,'Validation run',gaps.length?gaps.length+' issues to resolve':'Source validation passed',r.id);return {message:gaps.length?gaps.length+' issues need attention.':'Sources validated. The package is ready for review.'}}
  if(c.action==='approve'){requireValue(readiness(d,r).length===0,'Resolve validation issues before approval.');const gate=required(c.gate,'Approval stage');requireValue(Object.keys(r.gates).includes(gate),'Unknown approval stage.');if(gate==='finance')requireValue(finance(a),'Treasurer approval is required.');if(gate==='compliance')requireValue(compliance(a),'Compliance reviewer approval is required.');if(['committee','agm','signatures'].includes(gate))requireValue(governs(d,a),'Explicit governance authority is required.');const ref=required(c.reason,'Approval reference');if(['committee','agm','signatures'].includes(gate)){requireValue(c.fileId,'Attach the approved resolution or signature evidence.');file(d,c.fileId)}r.gates[gate]=true;r.approvals.push({stage:gate,reference:ref,actor:a.email,at:now(),fileId:c.fileId||null});r.status=Object.values(r.gates).every(Boolean)?'Approved':'Ready for review';event(d,a,'Approval recorded',r.title+' · '+gate,r.id);return {message:'Approval and evidence recorded.'}}
  if(c.action==='lock'){requireValue(compliance(a),'Compliance secretary or system owner access is required.');requireValue(readiness(d,r).length===0&&Object.values(r.gates).every(Boolean),'All validation and approval gates must pass.');const v={version:r.version,lockedAt:now(),lockedBy:a.email,snapshot:structuredClone(snapshot(d,r))};r.versions.push(v);r.status='Locked';event(d,a,'Report locked',r.title+' · v'+r.version,r.id);return {message:'Version locked. Exporting will not mark it filed.'}}
 }
 if(c.type==='submission'){
  requireValue(compliance(a),'Only compliance staff can record filings.');const r=c.reportId?find(d.reports,c.reportId):undefined;const o=c.obligationId?find(d.obligations,c.obligationId):undefined;requireValue(r||o,'Link this filing to an obligation or report.');if(r)requireValue(r.exportId&&['Exported','Filed'].includes(r.status),'Export the exact locked report version first.');const proof=file(d,required(c.fileId,'Official filing proof'));requireValue(proof,'Proof is required.');const sent=date(c.date,'Submission date');requireValue(sent<=new Date().toISOString().slice(0,10),'A filing date cannot be in the future.');const ref=required(c.reference,'Official reference',250);requireValue(!d.submissions.some(x=>x.reference===ref&&x.authority===(r?.authority||o?.authority)),'This authority reference is already recorded.');const s:Entry={id:uid(),title:r?.title||o!.title,status:'Filed',reportId:r?.id,obligationId:o?.id,authority:r?.authority||o?.authority,due:r?.due||o?.due,date:sent,method:required(c.method,'Submission method',100),reference:ref,fileId:proof.id,exportId:r?.exportId,version:r?.version||1,history:[]};s.history=[event(d,a,'Manual filing recorded',s.title+' · '+ref,s.id)];d.submissions.push(s);if(r)r.status='Filed';if(o)o.status='Filed';return {message:'Filing recorded with proof. Authority acceptance remains separate.'}
 }
 if(c.type==='response'){requireValue(compliance(a),'Compliance access is required.');const s=find(d.submissions,c.id);requireValue(['Accepted','Returned'].includes(c.status),'Choose the authority response.');file(d,required(c.fileId,'Official response evidence'));s.status=c.status;const reason=required(c.reason,'Response details');s.responses=[...(s.responses||[]),{status:c.status,reason,fileId:c.fileId,at:now(),actor:a.email}];s.history.push(event(d,a,'Authority response recorded',reason,s.id));s.responseFileId=c.fileId;if(s.obligationId)find(d.obligations,s.obligationId).status=c.status;return {message:'Authority response retained with the filed version.'}}
 if(c.type==='organization'){requireValue(owner(a),'Only the system owner can update the organization.');const p=c.values||{};if(p.mira!==d.organization.mira&&['Approved','Expired / removed'].includes(p.mira))file(d,required(p.fileId,'Official MIRA status evidence'));d.organization={...d.organization,name:required(p.name,'Legal name',250),dhivehi:text(p.dhivehi,250),registration:required(p.registration,'Registration number',250),registeredAt:date(p.registeredAt,'Registration date'),address:required(p.address,'Address',1000),mira:['Not recorded','Not applied','Application in progress','Approved','Expired / removed','Not applicable'].includes(p.mira)?p.mira:'Not recorded'};const o=d.obligations.find(o=>o.id==='o1');if(o&&!['Closed','Filed','Accepted'].includes(o.status)){const rule=d.rules.find(r=>r.id==='r1');o.due=rule?.months?addMonths(d.organization.registeredAt,rule.months):addDays(d.organization.registeredAt,rule?.days??90);}event(d,a,'Organization profile updated',d.organization.name);return {message:'Organization profile saved.'}}
 if(c.type==='record_status'){
  const kind=c.collection;requireValue(['members','assets'].includes(kind),'Unsupported lifecycle action.');requireValue(kind==='assets'?finance(a):compliance(a),'Your role cannot change this record.');const r=find(d[kind as 'members'|'assets'],c.id);const reason=required(c.reason,'Reason');const effective=date(c.date,'Effective date');if(kind==='members'){requireValue(['Active','Departed'].includes(c.status),'Choose a membership state.');r.departedAt=c.status==='Departed'?effective:null}else{requireValue(['In use','In storage','Disposed'].includes(c.status),'Choose an asset state.');if(c.status==='Disposed')file(d,required(c.fileId,'Disposal evidence'));r.disposalFileId=c.fileId||r.disposalFileId}r.status=c.status;r.history=[...(r.history||[]),event(d,a,'Lifecycle change recorded',r.title+' · '+c.status+' · '+reason,r.id)];return {message:'Record updated. Previous history is retained.'}
 }
 if(c.type==='deadline_decision'){
  requireValue(compliance(a),'Compliance access is required.');const o=find(d.obligations,c.id);requireValue(!['Filed','Accepted','Closed'].includes(o.status),'A filed or closed deadline cannot be rewritten.');const due=date(c.due,'Confirmed deadline');const reason=required(c.reason,'Source and applicability decision');o.originalDue=o.originalDue||o.due;o.deadlineHistory=[...(o.deadlineHistory||[]),{due:o.due,at:now(),actor:a.email,reason}];o.due=due;delete o.dueLabel;event(d,a,'Deadline applicability recorded',o.title+' · '+reason,o.id);return {message:'Deadline decision saved with the original date preserved.'}
 }
 if(c.type==='rule'){requireValue(owner(a),'Only the system owner can review rules.');const r=find(d.rules,c.id);const ref=required(c.reason,'Source review and applicability decision');r.previousVersions=[...(r.previousVersions||[]),{version:r.version,basis:r.basis,status:r.status,source:r.source,days:r.days,threshold:r.threshold,changeDays:r.changeDays}];r.version++;r.status='Reviewed';r.reviewedBy=a.email;r.reviewedAt=now();r.decision=ref;if(c.days!==undefined&&r.days!==undefined)r.days=positive(c.days,'Days');if(c.threshold!==undefined&&(r.threshold!==undefined||r.id==='r2'))r.threshold=positive(c.threshold,'Threshold');r.effective=date(c.effective,'Effective date');event(d,a,'Rule version reviewed',r.title+' · '+ref,r.id);return {message:'Rule review recorded. Existing deadlines are retained; changes need a separate applicability decision.'}}
 if(c.type==='case'){requireValue(compliance(a)||a.role==='Project sponsor','A sponsor or compliance reviewer must record recovery decisions.');const m=find(d.milestones,c.milestoneId);hasProject(d,a,m.projectId);const r:Entry={id:uid(),title:'Recovery · '+m.title,status:'Recovery required',projectId:m.projectId,milestoneId:m.id,owner:required(c.owner,'Support owner',250),due:date(c.due,'Recovery deadline'),reason:required(c.reason,'Evidence and support plan'),policy:'Draft · no automatic transfer',history:[]};requireValue(!d.cases.some(x=>x.milestoneId===m.id&&x.status!=='Resolved'),'An open case already exists for this milestone.');r.history=[event(d,a,'Recovery case opened',r.reason,r.id)];d.cases.push(r);return {message:'Recovery case opened with a named owner and deadline.'}}
 if(c.type==='resolve_case'){requireValue(compliance(a)||a.role==='Project sponsor','Sponsor or compliance access is required.');const r=find(d.cases,c.id);hasProject(d,a,r.projectId);const m=find(d.milestones,r.milestoneId);requireValue(m.status==='Accepted'&&m.acceptedAt&&m.acceptedAt>r.history[0].at,'Verify a new recovery output before clearing this risk.');r.status='Resolved';r.history.push(event(d,a,'Recovery verified',required(c.reason,'Verification decision'),r.id));return {message:'Recovery verified and case resolved.'}}
 throw new Error('Unsupported action.');
}
