export type Entry = {id:string;title:string;status:string;[key:string]:any};
export type History = {id:string;at:string;actor:string;action:string;detail:string;recordId?:string};
export type Milestone = Entry & {projectId:string;number:string;owner:string;reviewer:string;due:string;reviewDue:string;criteria:string[];result:string;submittedAt?:string;acceptedAt?:string;evidence?:string;fileId?:string;version:number;blocked?:boolean;blocker?:string;unblockOwner?:string;unblockDue?:string;history:History[]};
export type WorkspaceData = {organization:{name:string;dhivehi:string;registration:string;registeredAt:string;year:number;mira:string;address:string;timezone:string};projects:Entry[];milestones:Milestone[];obligations:Entry[];meetings:Entry[];members:Entry[];committee:Entry[];transactions:Entry[];donations:Entry[];assets:Entry[];activities:Entry[];reports:Entry[];submissions:Entry[];files:Entry[];rules:Entry[];audit:History[];cases:Entry[];mode:'sample'|'live'};
export type Collection = Exclude<keyof WorkspaceData,'organization'|'mode'|'audit'>;
export const now=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export function formatDate(date?:string,long=false){if(!date)return 'Not set';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',...(long?{year:'numeric'} as const:{}),timeZone:'Indian/Maldives'}).format(new Date(date.length===10?date+'T07:00:00Z':date))}
export function formatTime(date?:string){return date?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit',hour12:true,timeZone:'Indian/Maldives'}).format(new Date(date)):'Not recorded'}
export const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'MVR',maximumFractionDigits:0}).format(n||0);
export function addDays(date:string,days:number){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
const h=(at:string,actor:string,action:string,detail:string):History=>({id:at+action,at,actor,action,detail});
export function seedData():WorkspaceData{
 const milestones:Milestone[]=[
 {id:'m1',number:'01',title:'Scope and outline',status:'Accepted',due:'2026-09-03',reviewDue:'2026-09-04',reviewer:'Project lead',criteria:['Audience and learning outcomes are defined.','All planned sections have a clear purpose.'],result:'An agreed outline defines the audience, learning outcomes and six practical sections of the guide.',submittedAt:'2026-09-02T10:00:00Z',acceptedAt:'2026-09-03T06:00:00Z',evidence:'Scope-and-outline.md',version:1,history:[h('2026-09-01T04:00:00Z','Project lead','Commitment accepted','Content lead accepted the scope, dates and reviewer.'),h('2026-09-02T10:00:00Z','Content lead','Evidence submitted','Outline v1 submitted for review.'),h('2026-09-03T06:00:00Z','Project lead','Result accepted','The outline meets both acceptance criteria.')]},
 {id:'m2',number:'02',title:'Sources and examples',status:'Accepted',due:'2026-09-05',reviewDue:'2026-09-06',reviewer:'Editor',criteria:['References support the claims in every planned section.','Examples are accessible and usable by first-time website builders.','Remaining evidence gaps are identified.'],result:'Annotated references and usable examples map to every planned section of the guide.',submittedAt:'2026-09-04T11:00:00Z',acceptedAt:'2026-09-05T06:00:00Z',evidence:'Sources-and-examples.csv',version:1,history:[h('2026-09-01T04:00:00Z','Project lead','Responsibility assigned','Research contributor began the source collection.'),h('2026-09-03T04:00:00Z','Project sponsor','Planned handover','Content lead accepted the remaining research. Original contributor credit is retained.'),h('2026-09-04T11:00:00Z','Content lead','Evidence submitted','Annotated references v1 submitted to Editor.'),h('2026-09-05T06:00:00Z','Editor','Result accepted','All three acceptance criteria verified against evidence v1.')]},
 {id:'m3',number:'03',title:'First complete draft',status:'Submitted for review',due:'2026-09-08',reviewDue:'2026-09-10',reviewer:'Editor',criteria:['Every agreed section is present.','Examples are linked to the accepted sources.','Unresolved points are explicitly marked.'],result:'The complete six-section draft covers planning, structure, accessible content, publishing, and maintenance. Two open questions are marked for editorial review.',submittedAt:'2026-09-08T09:30:00Z',evidence:'First-website-guide-draft.md',version:1,history:[h('2026-09-06T04:00:00Z','Content lead','Work started','Draft follows the accepted outline and reference list.'),h('2026-09-08T09:30:00Z','Content lead','Evidence submitted','Complete draft v1 ready for editorial review.')]},
 {id:'m4',number:'04',title:'Review corrections',status:'In progress',due:'2026-09-11',reviewDue:'2026-09-12',reviewer:'Editor',criteria:['Reviewer comments are linked to changes or decisions.','Image permissions are documented.'],result:'',version:0,blocked:true,blocker:'Access to the shared image collection is needed to confirm usage rights.',unblockOwner:'Project lead',unblockDue:'2026-09-10',history:[h('2026-09-08T05:00:00Z','Content lead','Blocker reported','Requested image collection access. Independent corrections can continue.')]},
 {id:'m5',number:'05',title:'Final publication package',status:'Planned',due:'2026-09-14',reviewDue:'2026-09-14',reviewer:'Project lead',criteria:['Content has reviewer approval.','Accessible output and publication files are included.'],result:'',version:0,history:[h('2026-09-01T04:00:00Z','Content lead','Commitment accepted','Final package and review window agreed.')]},
 ].map(m=>({...m,owner:'Content lead',projectId:'ac-01'}));
 milestones.push({id:'m6',projectId:'ac-02',number:'01',title:'Interview guide and consent process',status:'In progress',owner:'Archive lead',reviewer:'Project sponsor',due:'2026-09-16',reviewDue:'2026-09-18',criteria:['Questions have been reviewed.','A consent and withdrawal process is included.'],result:'',version:0,history:[]});
 return {mode:'sample',organization:{name:'Atoll Commons',dhivehi:'އެޓޯލް ކޮމަންސް',registration:'10-NGO/CERT/2026/77',registeredAt:'2026-08-24',year:2026,mira:'Not applied',address:'Malé, Maldives',timezone:'Indian/Maldives'},milestones,
 projects:[{id:'ac-01',title:'First website learning guide',code:'AC–01',category:'Learning',description:'A practical public resource for building a first professional website.',status:'Active',health:'Evidence pending review',owner:'Project lead',sponsor:'Project sponsor',backup:'Deputy lead',due:'2026-09-14',start:'2026-09-01',budget:18000,approved:true,approvalRef:'Sample charter · 1 Sep 2026',policy:'Draft · not activated'},{id:'ac-02',title:'Island knowledge archive',code:'AC–02',category:'Community',description:'Preserving local knowledge through conversations, photographs and shared stories.',status:'Active',health:'On track',owner:'Archive lead',sponsor:'Project sponsor',backup:'Community coordinator',due:'2026-10-22',start:'2026-09-05',budget:12000,approved:true,policy:'Draft · not activated'},{id:'ac-03',title:'Community digital skills workshop',code:'AC–03',category:'Capacity building',description:'Making practical digital skills available to our community.',status:'Proposed',health:'Pre-start compliance',owner:'Programme lead',sponsor:'Project sponsor',backup:'Deputy lead',due:'2026-10-10',start:'2026-09-25',budget:32000,approved:false,policy:'Draft · not activated'}],
 obligations:[{id:'o1',title:'Hold the first general meeting',status:'Action needed',authority:'Registrar',due:'2026-11-22',owner:'Compliance secretary',ruleId:'r1',description:'Convene the first general meeting, record the election, and retain approved minutes and resolutions.',checklist:[{label:'Agree meeting date and venue',done:true},{label:'Prepare agenda and meeting notice',done:false},{label:'Record quorum, minutes and election',done:false},{label:'Attach approved resolution',done:false}]},{id:'o2',title:'Project information notice',status:'Blocked',authority:'Registrar',due:'2026-09-24',owner:'Compliance secretary',ruleId:'r2',projectId:'ac-03',description:'The proposed MVR 32,000 workshop meets the configured pre-start threshold. Retain filing proof before starting.',checklist:[{label:'Complete project charter and budget',done:true},{label:'Record President approval',done:false},{label:'Prepare and approve notice',done:false},{label:'Record manual submission and proof',done:false}]},{id:'o3',title:'Annual Registrar filing package',status:'Not due',authority:'Registrar',due:'2027-03-31',owner:'Compliance secretary',ruleId:'r4',description:'Prepare annual activities, accounts and the next-year programme. The sample deadline requires source review.',checklist:[{label:'Activity and membership records complete',done:true},{label:'Finance reconciled and approved',done:false},{label:'Committee and AGM resolutions attached',done:false},{label:'Signatures and supporting documents',done:false}]}],
 meetings:[{id:'meeting1',title:'September executive committee meeting',type:'Executive committee',status:'Scheduled',date:'2026-09-18',time:'16:00',location:'Malé · shared workspace',owner:'Compliance secretary',attendees:'President, Vice President, CFO, Compliance secretary',agenda:'1. Project progress and blockers\n2. First general meeting preparation\n3. Proposed continuity policy',minutes:'',resolution:'',quorum:3}],
 members:[1,2,3].map(i=>({id:'member'+i,title:'Founding member 0'+i,status:'Active',joined:'2026-08-24',email:'',type:'Founding member'})),committee:[{id:'c1',title:'President',person:'Founding member 01',status:'Interim',date:'2026-08-24',end:'2026-11-22'},{id:'c2',title:'Vice President',person:'Founding member 02',status:'Interim',date:'2026-08-24',end:'2026-11-22'},{id:'c3',title:'CFO / Treasurer',person:'Founding member 03',status:'Interim',date:'2026-08-24',end:'2026-11-22'}],
 transactions:[{id:'t1',title:'Founding contribution',type:'Income',amount:24000,date:'2026-08-24',category:'Member contributions',status:'Reconciled',projectId:'',evidence:'sample-receipt-01'},{id:'t2',title:'Website domain and hosting',type:'Expense',amount:1800,date:'2026-09-02',category:'Digital services',status:'Reconciled',projectId:'ac-01',evidence:'sample-receipt-02'},{id:'t3',title:'Community interview materials',type:'Expense',amount:650,date:'2026-09-06',category:'Programme costs',status:'Needs receipt',projectId:'ac-02'}],
 donations:[{id:'d1',title:'Founding contribution',donor:'Founding members',amount:24000,date:'2026-08-24',restriction:'Unrestricted',status:'Recorded',transactionId:'t1'}],assets:[{id:'a1',title:'Shared laptop',category:'Equipment',value:8500,date:'2026-08-26',custodian:'Project lead',status:'In use',location:'Malé · shared workspace'}],activities:[{id:'act1',title:'Learning guide planning session',date:'2026-09-01',projectId:'ac-01',location:'Online',participants:4,status:'Completed',description:'Agreed the learning outcomes, outline and responsibilities.',output:'Six-section outline and accepted milestone plan.'}],
 reports:['Annual Registrar report','Annual financial statements','Next-year programme & budget'].map((title,i)=>({id:'report'+(i+1),title,authority:'Registrar',year:i===2?2027:2026,status:i===2?'Not started':'Draft',version:1,due:'2027-03-31',narrative:i===0?'Atoll Commons was registered on 24 August 2026. Our initial programme focuses on accessible learning and community knowledge.':'',gates:{finance:false,compliance:false,committee:false,agm:false,signatures:false},approvals:[],versions:[]})),submissions:[],files:[],cases:[],
 rules:[{id:'r1',title:'First general meeting',basis:'90 days from registration',days:90},{id:'r2',title:'Pre-start project information',basis:'Project budget ≥ MVR 25,000',threshold:25000},{id:'r3',title:'Committee election and changes',basis:'First election: 30 days · later change: 15 days',days:30,changeDays:15},{id:'r4',title:'Annual Registrar package',basis:'Review the applicable annual deadline'},{id:'r5',title:'Approved charity annual filing',basis:'30 June following the calendar year; only while approved'}].map((r,i)=>({...r,status:i===4?'Not applicable':'Needs review',authority:i===4?'MIRA':'Registrar',version:1,source:i===4?'https://www.mira.gov.mv/Pages/View/charitiesobligations':'https://gazette.gov.mv/gazette/7062',effective:'2026-08-24'})),audit:[h('2026-09-08T09:30:00Z','Content lead','Evidence submitted','First complete draft · v1 awaits Editor review.'),h('2026-09-05T06:00:00Z','Editor','Milestone accepted','Sources and examples · approved evidence v1 retained.'),h('2026-09-01T04:00:00Z','Project lead','Project started','First website learning guide · sample charter approved.')]
 };
}
