'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Plus,Clock3,CircleCheck,LockKeyhole,FileSpreadsheet,ChevronDown,Flag,Users,ShieldCheck,Upload,ExternalLink,CalendarDays,Check,GitBranch} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {useApp,Status,Button,TabBar,EmptyState,Facts,Notice,FileLink,SearchBox,PageTitle,f} from '../ui';
import {formatDate,formatTime,money,type Milestone} from '@/lib/model';
export function Projects(){const {data,go,create}=useApp();const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const rows=data.projects.filter(p=>(filter==='all'||p.status===filter)&&[p.title,p.owner,p.category].join(' ').toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="OUR WORK" title="Projects" description="Shared purpose, clear responsibilities, and results you can verify." action={<Button primary onClick={()=>create('projects')}><Plus size={17}/> New project</Button>}/><div className="toolbar"><TabBar line={false} value={filter} onChange={setFilter} items={[{id:'all',label:'All projects',count:data.projects.length},{id:'Active',label:'Active'},{id:'Proposed',label:'Proposed'}]}/><SearchBox value={query} onChange={setQuery} placeholder="Search projects…"/></div><div className="project-grid">{rows.map(p=>{const ms=data.milestones.filter(m=>m.projectId===p.id);const accepted=ms.filter(m=>m.status==='Accepted').length;return <button key={p.id} className="project-card" onClick={()=>go('project/'+p.id)}><div className="card-topline"><span className="eyebrow">{p.code} / {p.category}</span><ArrowRight size={18}/></div><h2>{p.title}</h2><p>{p.description}</p><div className="project-card-status"><Status value={p.status}/><span>{p.owner}</span></div><div className="project-card-bottom"><div className="segmented-progress">{ms.map(m=><span key={m.id} className={m.status==='Accepted'?'done':m.status==='Submitted for review'?'review':''}/>)}</div><div><span>{accepted} of {ms.length} milestones accepted</span><span><CalendarDays size={14}/>{formatDate(p.due)}</span></div></div></button>})}</div>{!rows.length&&<EmptyState title="No projects here yet" description="Create a project with an accountable lead and a clear result."/>}<Notice><ShieldCheck size={18}/><span>Projects of MVR 25,000 or more receive a blocking pre-start notice under the initial rule configuration.</span></Notice></>}
export function ProjectWorkspace({id}:{id:string}){const app=useApp();const {data,go,route,form,run,create,tabPrefs,remember}=app;const p=data.projects.find(p=>p.id===id);const query=new URLSearchParams(route.split('?')[1]||'');const [section,setSection]=useState('milestones');const [view,setView]=useState(query.get('view')||tabPrefs[id]||'active');const [selected,setSelected]=useState(query.get('milestone')||'');
 const [detailOpen,setDetailOpen]=useState(!!query.get('milestone'));
 const detailHeaderRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const q=new URLSearchParams(route.split('?')[1]||'');if(q.get('view'))setView(q.get('view')!);if(q.get('milestone')){setSelected(q.get('milestone')!);setSection('milestones');setDetailOpen(true)}else{setDetailOpen(false)}},[route]);
 if(!p)return <EmptyState title="Project not available" description="This project does not exist or is outside your access." action={<Button onClick={()=>go('projects')}>All projects</Button>}/>;
 const ms=data.milestones.filter(m=>m.projectId===id);const completed=ms.filter(m=>m.status==='Accepted');const active=ms.filter(m=>m.status!=='Accepted');const list=view==='completed'?[...completed].sort((a,b)=>(b.acceptedAt||'').localeCompare(a.acceptedAt||'')):active;const m=ms.find(m=>m.id===selected);
 function choose(v:string){setView(v);remember(id,v);setSelected('');setDetailOpen(false)}
 function projectAction(action:string,title:string,fields:any[],initial?:any){form({title,fields,initial,submit:title,onSubmit:v=>run({type:'project',id,action,...v})})}
 return <Sheet open={detailOpen&&!!m} onOpenChange={setDetailOpen}><button className="back-link" onClick={()=>go('projects')}><ArrowLeft size={16}/> All projects</button><div className="page-heading"><div><div className="eyebrow">{p.code} <span>/</span> {p.category.toUpperCase()}</div><h1>{p.title}</h1><p className="subtitle">{p.description}</p></div><Button onClick={()=>app.inspect('projects',id)}><ExternalLink size={16}/> Project brief</Button></div><div className="project-meta"><Status value={p.status}/><span>Final delivery <b>{formatDate(p.due,true)}</b></span><span className="meta-divider"/><span>Lead <b>{p.owner}</b></span><div className="team-avatars"><span>PL</span><span>CL</span><span>ED</span></div></div><TabBar value={section} onChange={setSection} items={[{id:'milestones',label:'Milestones',count:ms.length},{id:'team',label:'Team & continuity'},{id:'evidence',label:'Evidence & files'},{id:'activity',label:'Activities'}]}/>
 {section==='milestones'&&<><div className="section-heading"><div><h2>Small steps. Meaningful results.</h2><p>{completed.length} of {ms.length} milestones accepted <span className="dot-divider">·</span> {ms.filter(m=>m.status==='Submitted for review').length} awaiting review</p></div><div className="heading-actions"><div className="mini-progress">{ms.map(x=><span key={x.id} className={x.status==='Accepted'?'done':x.status==='Submitted for review'?'review':''}/>)}</div><Button small onClick={()=>create('milestones',id)}><Plus size={15}/> Milestone</Button></div></div><TabBar line={false} value={view} onChange={choose} items={[{id:'active',label:'Active',count:active.length},{id:'completed',label:'Completed',count:completed.length}]}/><p className="list-description">{view==='completed'?'Accepted results, with the evidence and decisions that support them.':'The next results to deliver, review, and move forward.'}</p><div className="milestone-list">{list.map(x=><SheetTrigger key={x.id} onClick={()=>setSelected(x.id)} className={'milestone-card '+(x.id===m?.id?'selected':'')}><div className={'milestone-icon '+(x.status==='Accepted'?'accepted':'')}>{x.status==='Accepted'?<CircleCheck size={20}/>:x.status==='Submitted for review'?<Clock3 size={20}/>:<span>{x.number}</span>}</div><div className="milestone-card-content"><h3><span>{x.number} · </span>{x.title}</h3><p>{x.owner} <span>·</span> {x.reviewer}</p><div className="inline-badges"><Status value={x.status}/>{x.blocked&&<Status value="Blocked"/>}</div><div className="milestone-dates"><span>{view==='completed'?'Original due':'Output due'} <b>{formatDate(x.due)}</b></span><span>{view==='completed'?'Accepted':'Review due'} <b>{formatDate(view==='completed'?x.acceptedAt:x.reviewDue)}</b></span></div></div><ArrowRight className="card-arrow" size={17}/></SheetTrigger>)}</div>{!list.length&&<EmptyState title={view==='completed'?'No accepted milestones yet':'No active milestones'} description={view==='completed'?'Reviewer-accepted results will appear here.':'The project retains its own completion criteria.'} action={<Button small onClick={()=>choose(view==='completed'?'active':'completed')}>{view==='completed'?'View Active':'View Completed'}</Button>}/>}<div className="quiet-note"><LockKeyhole size={16}/><p>Completed means reviewer-accepted.<br/>Original deadlines, credit and evidence stay attached.</p></div></>}
 {section==='team'&&<div className="two-column"><section className="panel"><div className="panel-heading"><h2>People & responsibilities</h2><Users size={20}/></div>{[{label:'Accountable lead',name:p.owner},{label:'Project sponsor',name:p.sponsor},{label:'Continuity deputy',name:p.backup}].map((r,i)=><div className="person-row" key={r.label}><span className={'avatar person-'+i}>{r.name.slice(0,2).toUpperCase()}</span><div><h3>{r.name}</h3><p>{r.label}</p></div><span className="badge neutral">{i===2?(p.backupAccepted?'Accepted':'Awaiting consent'):'Assigned'}</span></div>)}{!p.backupAccepted&&<Button small onClick={()=>projectAction('backup','Accept backup responsibility',[],{})}><Check size={16}/> {data.mode==='sample'?'Simulate deputy acceptance':'Accept as deputy'}</Button>}<h4>Milestone commitments</h4>{ms.map(m=><div className="compact-row" key={m.id}><span>{m.title}<small>{m.owner}</small></span><Status value={m.commitmentAccepted||m.status!=='Planned'?'Accepted':'Planned'}/></div>)}</section><section className="panel"><div className="panel-heading"><h2>Continuity policy</h2><ShieldCheck size={21}/></div><Status value="Needs review"/><p className="panel-copy">Automatic monitoring and interim transfers are inactive. The proposed response windows and succession route need formal approval and participant notification.</p><Facts items={[["Proposed response window",'Up to 48 elapsed hours'],['Successor confirmation','Within 24 elapsed hours'],['Recovery verification','First output within 2 calendar days'],['Timezone','Indian/Maldives']]}/><Notice tone="amber">These are internal policy proposals, not legal deadlines. Recording a backup does not activate automatic transfers.</Notice><Button onClick={()=>go('health')}><GitBranch size={16}/> Open project health</Button></section></div>}
 {section==='evidence'&&<><div className="section-heading"><div><h2>The evidence behind the work</h2><p>Versioned outputs and shared project records.</p></div><Button onClick={()=>form({title:'Add project evidence',projectId:id,fields:[f('fileId','Evidence file','file')],submit:'Done',onSubmit:async()=>{}})}><Upload size={16}/> Upload evidence</Button></div><div className="evidence-grid">{data.files.filter(f=>f.projectId===id).map(f=><article className="panel" key={f.id}><FileLink id={f.id}/><p className="metadata">{formatDate(f.createdAt)} · {(f.size/1024).toFixed(0)} KB</p><small className="muted">SHA-256 {f.sha256?.slice(0,16)}…</small></article>)}{ms.filter(m=>m.evidence&&!m.fileId).map(m=><details className="evidence-card" key={m.id}><summary><FileSpreadsheet size={20}/><span>{m.evidence}<small>{data.mode==='sample'?'Sample evidence summary':'Structured outcome'} · v{m.version}</small></span><ChevronDown size={16}/></summary><div className="evidence-summary">{m.result}<SheetTrigger className="text-link" onClick={()=>setSelected(m.id)}>View result and history <ArrowRight size={14}/></SheetTrigger></div></details>)}</div>{!data.files.some(f=>f.projectId===id)&&!ms.some(m=>m.evidence)&&<EmptyState title="No project evidence yet" description="Upload the documents that support this project’s results."/>}</>}
 {section==='activity'&&<><div className="section-heading"><h2>Project activities</h2><Button onClick={()=>create('activities',id)}><Plus size={16}/> Record activity</Button></div>{data.activities.filter(a=>a.projectId===id).map(a=><article className="panel activity-card" key={a.id}><div className="card-topline"><h3>{a.title}</h3><span className="metadata">{formatDate(a.date)}</span></div><p className="panel-copy">{a.output}</p><span className="metadata">{a.location} · {a.participants} participants</span></article>)}{!data.activities.some(a=>a.projectId===id)&&<EmptyState title="No activities recorded"/>}</>}
 {p.status==='Proposed'&&<Notice tone="amber"><Flag size={18}/><span>Awaiting project approval and pre-start checks.</span><Button small onClick={()=>projectAction('approve','Record project approval',[f('reason','Resolution / approval reference','textarea')])}>Record approval</Button></Notice>}{p.status==='Approved'&&<Notice><ShieldCheck size={18}/><span>Approval recorded. Check commitments, backup consent, and filing proof before launch.</span><Button small onClick={()=>run({type:'project',id,action:'start'})}>Start project</Button></Notice>}
 <SheetContent className="milestone-sheet" initialFocus={detailHeaderRef}>
  <SheetHeader ref={detailHeaderRef} tabIndex={-1}>
   <SheetTitle>{m?.title}</SheetTitle>
   <SheetDescription>{p.code} · {p.title}</SheetDescription>
  </SheetHeader>
  <div className="milestone-sheet-body">{m&&<MilestoneDetail key={m.id+':'+m.status} m={m}/>}</div>
 </SheetContent>
 </Sheet>}
function MilestoneDetail({m}:{m:Milestone}){const {data,run,form,go}=useApp();const [checks,setChecks]=useState<boolean[]>(m.criteria.map(()=>false));const accepted=m.status==='Accepted';const sample=data.mode==='sample';const ontime=m.submittedAt?new Date(m.submittedAt)<=new Date(m.due+'T18:59:59Z'):false;const reviewLate=m.acceptedAt?new Date(m.acceptedAt)>new Date(m.reviewDue+'T18:59:59Z'):false;
 const act=(action:string,title:string,fields:any[],submit?:string)=>form({title,projectId:m.projectId,fields,submit:submit||title,onSubmit:v=>run({type:'milestone',id:m.id,action,...v})});
 return <article className="detail-panel"><div className="detail-top"><span className="eyebrow">MILESTONE {m.number}</span><span className="badge neutral">{accepted?<LockKeyhole size={14}/>:<Clock3 size={14}/>} {accepted?'Read only':'Work record'}</span></div><Status value={m.status}/>{accepted&&<span className="acceptance-label">accepted by {m.reviewer}</span>}<Facts items={[[accepted?'Owner at completion':'Accountable owner',m.owner],['Original output due',formatDate(m.due)],['Output submitted',formatTime(m.submittedAt)],[accepted?'Completed / accepted':'Review due',accepted?formatTime(m.acceptedAt):formatDate(m.reviewDue)],['Reviewer',m.reviewer]]}/>{m.submittedAt&&<p className={ontime?'success-text':'warning-text'}><CircleCheck size={15}/>{ontime?'Output submitted on time.':'Output submitted after the original deadline.'}{reviewLate&&' Review accepted after the review deadline.'}</p>}{m.blocked&&<div className="blocker-card"><div className="card-topline"><h4><Flag size={15}/> Input needed</h4><Status value="Blocked"/></div><p>{m.blocker}</p><small>{m.unblockOwner} · resolve by {formatDate(m.unblockDue)}</small><Button small onClick={()=>act('resolve','Resolve blocker',[f('reason','What changed / resolution evidence','textarea')])}>Record resolution <ArrowRight size={14}/></Button></div>}{m.returnReason&&!accepted&&<Notice tone="amber">Changes requested: {m.returnReason}</Notice>}
 <h4>{accepted?'Accepted result':'Submitted result'}</h4><p className="result-copy" dir="auto">{m.result||'The agreed result will be recorded here with its supporting evidence.'}</p>{m.fileId?<div className="evidence-card retained-file"><FileLink id={m.fileId}/><small>Retained evidence · v{m.version}</small></div>:m.evidence&&<details className="evidence-card"><summary><FileSpreadsheet size={20}/><span>{m.evidence}<small>{accepted?'Accepted':'Submitted'} evidence version · {sample?'sample':'structured outcome'}</small></span><ChevronDown size={16}/></summary><div className="evidence-summary">{m.result}<p>{sample?'This is an illustrative evidence summary.':'This structured outcome is retained as part of the evidence record.'}</p></div></details>}
 <h4>Acceptance criteria</h4><ul className="criteria">{m.criteria.map((c,i)=><li key={c}>{m.status==='Submitted for review'?<Checkbox checked={checks[i]} onCheckedChange={v=>setChecks(old=>old.map((x,j)=>i===j?!!v:x))} aria-label={c}/>:<CircleCheck size={16}/>}<span>{c}</span></li>)}</ul>
 {m.status==='Submitted for review'&&<div className="review-actions"><p className="metadata">{sample?'Sample review: act as the assigned reviewer.':'Only the assigned reviewer can accept this result.'}</p><div className="button-row"><Button primary disabled={!checks.every(Boolean)||m.blocked} onClick={async()=>{await run({type:'milestone',id:m.id,action:'accept',checks});go('project/'+m.projectId+'?view=completed&milestone='+m.id)}}><Check size={16}/> Accept result</Button><Button onClick={()=>act('return','Request changes',[f('reason','Specific acceptance gaps','textarea')])}>Request changes</Button></div></div>}
 {!accepted&&m.status!=='Submitted for review'&&<div className="review-actions"><div className="button-row"><Button primary onClick={()=>act('submit','Submit milestone evidence',[f('result','Concrete result / findings','textarea',{help:'Describe the output against the agreed acceptance criteria.'}),f('fileId','Supporting file','file',{required:false}),f('structured','Use this text as structured evidence','checkbox',{required:false,help:'Appropriate for a decision record or structured findings. A generic status update is not evidence.'})],'Submit for review')}><Upload size={16}/> Submit evidence</Button>{!m.blocked&&<Button onClick={()=>act('block','Report a blocker',[f('reason','What is missing and what was tried','textarea'),f('owner','Who can unblock this?'),f('due','Latest useful resolution date','date')])}><Flag size={16}/> Blocker</Button>}</div>{m.commitmentAccepted===false&&<button className="text-link" onClick={()=>run({type:'milestone',id:m.id,action:'commit'})}>Accept this commitment <ArrowRight size={14}/></button>}</div>}
 <h4>Responsibility & approval history</h4><div className="timeline">{m.history.map(h=><div key={h.id}><small>{formatDate(h.at)} <span>· {h.actor}</span></small><b>{h.action}</b><p>{h.detail}</p></div>)}</div>{m.cycles?.length>0&&<details className="history-cycles"><summary>Earlier accepted cycles ({m.cycles.length})</summary>{m.cycles.map((v:any,i:number)=><div key={i}><h4>Accepted evidence v{v.version}</h4><p>{v.result}</p><p className="metadata">Submitted {formatTime(v.submittedAt)} · accepted {formatTime(v.acceptedAt)}</p>{v.fileId&&<FileLink id={v.fileId}/>}</div>)}</details>}{accepted&&<button className="text-link subtle-link" onClick={()=>act('reopen','Open a correction cycle',[f('reason','Reason for correction','textarea')])}>Record an authorized correction <ArrowRight size={13}/></button>}
 </article>}
